### ISSUE TITLE
Issue #5 - User can search entries

### ISSUE THREAD

**Issue by easton-morris** [easton-morris/code-journal#9]
## 💰 Motivation

Journal owners will want to search their many journal entries. 

## 📐 Plan

Create a search bar in the header that users can input values for. 

## ✅ Task List

- [x] create search input in the header with a sensible placeholder value
- [x] create search button for initiating the search
- [x] add an event listener to the search button
- [ ] create a function that checks the value of the search bar against the values in the titles
- [ ] make the function return a list of entry id's that have matches
- [ ] use the event listener to call the search check function and also reload the DOM with only the matched entries
- [ ] have all items load if there is no value in the search bar
- [ ] reset the search bar value to an empty string once searched
- [ ] clean up styling
- [ ] test in a private session
